### ISSUE TITLE
Setup Windows build on AppVeyor

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-test-example-repos#1]
Can we clone each repo and test on Windows?

**Comment by brian-mann** [comment]
This is working (the cloning bits) but Windows is not stopping the server processes (even though we're telling it to) and thus after the first example repo runs, the next one fails due to port binding.

**Comment by bahmutov** [comment]
Need to see running processes before and after `Stop-Process` command, can use `Get-Process` https://technet.microsoft.com/en-us/library/ee176855.aspx

**Comment by bahmutov** [comment]
Hmm, the stupid thing does not stop the process on CI, even if this command is working on Windows terminal
```
[?25hGet-Process -Name cmd | Stop-Process
cd ..
echo ***
***
echo *** cypress-example-kitchensink ***
*** cypress-example-kitchensink ***
```

**Comment by bahmutov** [comment]
Finally working
